config/routes.rb
Rails.application.routes.draw do

root 'events#index'
devise_for :users

resources :events
resources :users
resources :attendances
resources :home, only: [:index]
resources :charges

get "events/subscribe/:id", to: "attendances#subscribe", as:"attendance_subscription"
#get "events/:id/:id", to: "events#adduser"
post "events/subscribe/:id", to: "attendances#subscribe"

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

	belongs_to :user
	belongs_to :event

	after_create :participation_send

  def participation_send
    AttendanceMailer.participation_email(self).deliver_now
    puts "Je suis dans le modele"
  end

end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :admin, class_name: 'User'

validates :title, presence: true, length: { in: 5..140}

validates :description, presence: true, length: { in: 20..1000}

validates :price, presence: true
validates_numericality_of :price, :greater_than => 1, :less_than => 1000


validates :location, presence: true


validates :duration, presence: true
validate :duration_is_a_multiple_of_five


validates :start_date, presence: true
validate :start_date_cannot_be_in_the_past

 # Method to prevent creating past events

  def start_date_cannot_be_in_the_past

    if start_date.present? && start_date < Date.today

      errors.add(:start_date, "L'évènement ne peut pas être créer dans le passé.")

    end

  end

  

  # Method to verify multiple of 5

  def duration_is_a_multiple_of_five

    unless duration.present? && duration % 5 == 0

      errors.add(:duration, "Doit être un multiple de 5")

    end

  end


end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	has_many :attendances
	has_many :events, through: :attendances
	has_many :events, foreign_key: 'admin_id'


#  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }

# validates :user_name, presence: true, length: { minimum: 2 }
# validates :encrypted_password,  presence: true, length: { in: 1...15 }

after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

	before_action :authenticate_admin, only: [:index]
	#before_action :already_attendance_or_admin

	def index
		@event = Event.find(params[:event_id])
		@all_attendances = @event.attendances
	end

	def new
		@event = Event.find(params[:event_id])
		@attendance = Attendance.new
	end

	def subscribe
		@event = Event.find(params[:id])
		if @event.attendances.include? current_user
			flash[:error] = "Vous participez deja a l event"
			redirect_to @event
		end

		  # Amount in cents # permet de renvoyer sur le paiement pour la participation
		  @amount = @event.price*100

		  customer = Stripe::Customer.create(
		  	:email => params[:stripeEmail],
		  	:source  => params[:stripeToken]
		  	)

		  charge = Stripe::Charge.create(
		  	:customer    => customer.id,
		  	:amount      => @amount,
		  	:description => 'Rails Stripe customer',
		  	:currency    => 'usd'
		  	)

		  	 @attendance = Attendance.new(stripe_customer_id: charge[:customer], user: current_user, event: @event)
		  	 if @attendance.save
		  	  redirect_to @event
		  	  return
		  	    else
		  	    	flash[:danger] = "Les infos sont incomplets"
		  	    	 render :new 
		  	    	end
		rescue Stripe::CardError => e
			flash[:error] = e.message
			redirect_to @event
		end 

	def edit
	end

	def show
	end

	private

	def authenticate_admin
		@event = Event.find(params[:event_id])
		unless current_user == @event.admin
			flash[:danger] = "Cette section est reservee aux administrateurs des events"
			redirect_to event_path(params[:event_id])
		end
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user, only: [:new]
	def index
		@events = Event.all

	end 


	def show
		@event= Event.all.find(params[:id].to_i)
		puts '@' * 30
		puts params
		puts '@' * 30

	end 

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(title: params[:title], description: params[:description], price: params[:price].to_i, location: params[:location], admin: current_user, start_date: params[:start_date], duration: params[:duration])

		if @event.save
			redirect_to root_path
		else
			flash[:danger] = "Il manque des informations"
			render :new 
		end
	end

	def edit
		@event = Event.find(params[:id])
	end 
	def update
		@event = Event.find(params[:id])
		event_params = Hash.new {   }
		event_params = params.require(:event).permit(:title, :description)

		@event.update(event_params)
		if @event.update(event_params)
			"Bravo tu as cree un new Event"
			redirect_to root_path
		else
			render :edit
		end 
	end

	def destroy
		puts "hellllllllllllooooooooooooooooooooooo"
		puts params[:id]
		@event = Event(params[:id])
		@event.destroy
		@event.save
		redirect_to root_path
	end 

	private

	def authenticate_user
		unless current_user
			flash[:danger] = "Merci de vous connecter"
			redirect_to login_path
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


	before_action :authenticate_user!, only: [:secret]


	def index
	end


	def secret
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.all
	end

	def show
		@user= User.all.find(params[:id].to_i)
		puts '@' * 30
		puts params
		puts '@' * 30
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.hmtl.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-currency = 'eur'
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<h1> Editer l'Event </h1>
<%= form_for @event do |f| %>
<div class="form-group">
	<label> Titre de l'Event </label>
	<%= f.text_field :title, class: 'form-control' %>
</div>
<%= form_for @event do |f| %>
<div class="form-group">
	<label> Description de l'Event </label>
	<%= f.text_area :description, class: 'form-control' %>
</div>
<div class-"form-group">
	<button type="submit">Modifier l'Event</button>
</div>
<% end %>
<% end %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bienvenue sur Eventbrite</title>
</head>
<body >


	<h3> <center> Bienvenue sur Eventbrite <center></h3>

</body>
</html>

<% @events.each do |event| %>
<div class="col-sm-6">
<div class="card text-center" style="width: 18rem;">
<div class="mx-auto" style="width: 600px;">

  <img class="card-img-top" style="width: 350px;" src="https://partyflock.nl/ov/images/party/346121_620x413_460681/Downtown-Beach-Party.jpg" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">	<%= event.location%></h5>
    <p class="card-text"><p>  <%= event.title %>  </p>
    <p class="card-text"><p>  <%= event.description %>  </p>
    <p class="btn btn-info"> <%= link_to "Voir l'Event.", event_path(event.id) %></p>
    <td> <%= button_to "Modifier", edit_event_path(event.id), class: "btn btn-primary", method: "get"   %>
    <td> <%= button_to "Supprimer l'Event", event_path(event.id), method: "delete", class: "btn btn-danger", data: { confirm: "Vous-êtes vraiment sur ?"} %></td> 
	</div>
</br></br>
  </div>
	</div>
</div>
<% end %>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Event creation process failed due to:</p>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>
  <h6 class=text-info>Titre</h6>
  <%= text_field_tag 'title', '', class: 'form-control', placeholder: 'Ex: Mon anniversaire'%>
  <p class="small">Doit être compris entre 5 et 140 caractères.</p></br>
  <h6 class=text-info>Prix</h6>
  <%= text_field_tag 'price', '', class: 'form-control', placeholder: 'Ex: 25'%>
  <p class="small">Doit être un chiffre entier positif.</p></br>
  <h6 class=text-info>Lieu</h6>
  <%= text_field_tag 'location', '', class: 'form-control', placeholder: 'Ex: Lyon'%></br>
  <h6 class=text-info>Date</h6>
  <%= text_field_tag 'start_date', '', class: 'form-control', placeholder: 'Ex: 2019/11/01'%>
  </br>
  <h6 class=text-info>Durée</h6>
  <%= text_field_tag 'duration', '', class: 'form-control', placeholder: 'Ex: 60 minutes'%>
  <p class="small">Doit etre un multiple de 5 (60min, 100min, ...)</p></br>
  <h6 class=text-info>Description</h6>
  <%= text_area_tag 'description', '', class: 'form-control', placeholder: 'Lieu exact de la rencontre, artistes presents, cad tous les renseignements possibles'%>

  <%= submit_tag "Créer l'Event", class: "btn btn-info" %></br>
<% end %>
<p></p>

app/views/events/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Event selectionne.</title>
</head>
<body >
	<center>
		<div class="col-sm-6">
			<div class="card text-center" style="width: 18rem;">
				<div class="mx-auto" style="width: 600px;">

					<img class="card-img-top" style="width: 350px;" src="https://i.pinimg.com/originals/6d/7f/16/6d7f16413de6c9799d5e2ba49c5f3d23.jpg" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title">	Titre: <%= @event.title %> </h5>
						<p class="card-text"><p>  La description : <%= @event.description %> </p>
						<p class="card-text"><p>  Duree de l'Event : <%= @event.duration %>  </p>
						<p class="card-text"><p>  Ville : <%= @event.location %>  </p>
						<p class="card-text"><p>  Date : <%= @event.start_date %>  </p>
						<p class="card-text"><p>  Nombre d'inscrits : <%= @event.attendances.count %> </p>
						<%= form_tag attendance_subscription_path do %>
						<article>
							<% if flash[:error].present? %>
							<div id="error_explanation">
								<p><%= flash[:error] %></p>
							</div>
							<% end %>
							<label class="amount">
								<span>Pour rejoindre l event, payez son prix : <%= @event.price.to_f / 100%> euros</span>
							</label>
						</article>

						<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
						data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
						data-description="A month's subscription"
						data-amount="<%= @event.price%>"
						data-currency="eur"
						data-locale="auto"></script>
						<% end %>


						<div class="well">
						</div> 

						<h1> La liste des participants </h1>

						<table class = "table table-striped">
							<tr>
								<th> Nom </th>
								<th> Adresse email </th>
								<th> </th>
							</tr>
							<% @event.attendances.each do |attendance|%>
							<td> <%= attendance.user.first_name%> </td>
							<td> <%= attendance.user.email %> </td>
							<td> <%= link_to('voir le profil du participant', user_path(attendance))%></td>
						</tr>
						<% end %>
					</table>
					<br/>
					<br/>
				</div>

			</div>
		</div>
	</p>
</center>
</body>
</html>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>

 <title>Event</title>

    <%= csrf_meta_tags %>

    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <title>Accueil</title>

  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  </head>

  <body>

    <nav class="navbar navbar-inverse" style="background-color: #000000">

  <div class="container-fluid">

    <ul class="nav navbar-nav">

      <li><%= link_to "Home", events_path %></li>

      <li><%= link_to "Créer un evenement", new_event_path %></li>
      <li><%= link_to "Qui sont les organisateurs ?", users_path %></li>

    </ul>

    <form class="btn pull-right">

    <div class="dropdown">

    <li class="nav-item">

            <% if signed_in? %>

            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">

            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>

             <span class="caret"></span>

            </button>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

            <li><%= link_to 'Mon profil', user_path(current_user), class:'login text-decoration-none' %></li>

            <li><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></li>

            

            <% else %>

            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">

            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>

             <span class="caret"></span>

            </button>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">

            <li><%= link_to "S'inscrire", new_user_registration_path, class:'login text-decoration-none' %></li>

           <li><%= link_to 'Se connecter', new_user_session_path, class:'login text-decoration-none' %></li>

           

            <% end %>

          </li>

  </div>

    </form>

  </div>

</nav>

    

    <%= yield %>

  </body>

</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bienvenue sur Eventbrite</title>
</head>
<body >


	<h3> <center> Bienvenue sur Eventbrite <center></h3>

</body>
</html>

<%@user.each do |user| %>
<div class="col-sm-6">
<div class="card text-center" style="width: 18rem;">
<div class="mx-auto" style="width: 600px;">

  <img class="card-img-top" style="width: 350px;" src="https://pngimage.net/wp-content/uploads/2018/06/funny-png-pictures-4.png" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">	<%=user.first_name%></h5>
    <p class="card-text"><p>  <%= user.description %>   </p>
    <p class="card-text"><p>  <%= user.email %>  </p>
    <p class="btn btn-info"> <%= link_to "voir le profil de l utilisateur", user_path(user.id) %></p>
    <br/>
    <br/>
	</div>

  </div>
	</div>
</div>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body >

	<h3> <center> Presentation de l'organisateur de l'Event<center></h3>
		<center>
<div class="col-sm-6">
<div class="card text-center" style="width: 18rem;">
	<div class="mx-auto" style="width: 600px;">
 <img class="card-img-top" style="width: 350px;" src="https://nerdgirlpower.files.wordpress.com/2016/04/chuck-norris-1.png" alt="Card image cap">
  <div class="card-body">
 <h5 class="card-title">	Prenom de l'organiseur : <%= @user.first_name %></h5>
    <p class="card-text"><p>  Nom de famille : <%= @user.last_name %> </p>
    <p class="card-text"><p>  Description  : <%= @user.description %>  </p>
    <p class="card-text"><p>  Email : <%= @user.email%>  </p>
    <br/>
    <br/>
	</div>

  </div>
	</div>
</div>
</center>